apiServer: {{ .apiServer }}
controlVIP: {{ .controlVIP }}
vpcVLANRange:
  min: {{ .vpcVLANMin }}
  max: {{ .vpcVLANMax }}
users:
{{ range .users }}
- name: {{ .Name }}
  password: {{ .Password }}
  role: {{ .Role }}
  sshKeys:
  {{ range .SSHKeys }}
  - "{{ . }}"
  {{ end }}
{{ end }}
agentRepo: {{ .agentRepo }}
agentRepoCA: |
{{ .agentRepoCA | indent 2 }}
dhcpdConfigMap: fabric-dhcp-server-config
dhcpdConfigKey: dhcpd.conf
vpcBackend: {{ .vpcBackend }}
snatAllowed: {{ .snatAllowed }}
vpcSubnet: {{ .vpcSubnet }}
fabricMode: {{ .fabricMode }}
vs: {{ .vs }}
