node-name: "{{ .controlNodeName }}"
cluster-cidr: {{ .cfg.ClusterCIDR }}
service-cidr: {{ .cfg.ServiceCIDR }}
cluster-dns: {{ .cfg.ClusterDNS }}
write-kubeconfig-mode: "0644"
tls-san:
  {{ range .cfg.TLSSAN }}
  - {{ . }}
  {{ end }}
secrets-encryption: true
cluster-init: true
