# Copyright 2023 Hedgehog
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

replicaCount: 1
image:
  repository: {{ .ref.RepoName }}
  pullPolicy: IfNotPresent
  tag: {{ .ref.Tag }}
serviceAccount:
  create: true
  annotations: {}
  name: ""
service:
  type: ClusterIP
  port: 5000

persistence: true
pvc:
  create: true
  storage: 30Gi

secretFiles: {}
externalSecrets:
  - secretName: zot-secret
    mountPath: /secrets

httpGet:
  scheme: HTTPS

mountConfig: true
configFiles:
  config.json: |-
    {
      "log": { "level": "debug" },
      "storage": { "rootDirectory": "/var/lib/registry" },
      "http": {
        "address": "0.0.0.0",
        "port": "5000",
        "tls": {
          "cert": "/secrets/cert.pem",
          "key": "/secrets/key.pem"
        }
      }
    }
