# permissions for end users to view fabricators.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: fabricator-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: fabricator
    app.kubernetes.io/part-of: fabricator
    app.kubernetes.io/managed-by: kustomize
  name: fabricator-viewer-role
rules:
- apiGroups:
  - fabricator.githedgehog.com
  resources:
  - fabricators
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fabricator.githedgehog.com
  resources:
  - fabricators/status
  verbs:
  - get
